// Insertar Acronimos
export const AGREGAR_ACRONIMO = 'AGREGAR_ACRONIMO'
export const AGREGAR_ACRONIMO_EXITO = 'AGREGAR_ACRONIMO_EXITO'
export const AGREGAR_ACRONIMO_ERROR = 'AGREGAR_ACRONIMO_ERROR'


// Consultar Acronimos
export const COMENZAR_CONSULTA = 'COMENZAR_CONSULTA'
export const COMENZAR_CONSULTA_EXITO = 'COMENZAR_CONSULTA_EXITO'
export const COMENZAR_CONSULTA_ERROR = 'COMENZAR_CONSULTA_ERROR'


// Consultar significado API
export const COMENZAR_CONSULTA_API = 'COMENZAR_CONSULTA_API'
export const COMENZAR_CONSULTA_API_EXITO = 'COMENZAR_CONSULTA_API_EXITO'
export const COMENZAR_CONSULTA_API_ERROR = 'COMENZAR_CONSULTA_API_ERROR'